#pragma once

#define NO_GLFW_INCLUDE
#include "common.h"
#include "TinyObjWrapper.h"
#undef NO_GLFW_INCLUDE

constexpr unsigned int NUM_RAYTYPES = 2; // 0: radiance, 1: volume

constexpr OptixPayloadTypeID RADIANCE_PAYLOAD_TYPE = OPTIX_PAYLOAD_TYPE_ID_0;
constexpr OptixPayloadTypeID VOLUME_PAYLOAD_TYPE = OPTIX_PAYLOAD_TYPE_ID_1;

enum DoneReason {
  MISS,
  MAX_DEPTH,
  RUSSIAN_ROULETTE,
  LIGHT_HIT,
  ABSORBED,
  VOLUME_BOUNDARY,
  NOT_DONE
};

struct RadiancePayloadRayData {
  float3 attenuation; // Accumulated ray color
  unsigned int randomSeed; // Current random seed used for Monte Carlo sampling
  int depth; // Current recursion depth
  float3 emissionColor; // Emission color of the current surface
  float3 radiance; // Accumulated radiance
  //float importance; // Importance of the current path TODO: Implement this
  float3 origin; // Origin of the current ray
  float3 direction; // Direction of the current ray
  int done; // Flag to indicate if the current path is done
  DoneReason doneReason; // Reason why the current path is done
}; // 19 parameters

struct VolumePayLoadRayData {
  float3 attenuation;         //  3 idx 0, 1, 2
  unsigned int randomSeed;    //  1 idx 3
  int step;                   //  1 idx 4
  float3 emissionColor;       //  3 idx 5, 6, 7
  float3 radiance;            //  3 idx 8, 9, 10
  float3 origin;              //  3 idx 11, 12, 13
  float3 direction;           //  3 idx 14, 15, 16
  int done;                   //  1 idx 17
  DoneReason doneReason;      //  1 idx 18
  float tMax;                 //  1 idx 19
  OptixAabb volumeAabb;       // +6 idx 20, 21, 22, 23, 24, 25
                              //----
};                            // 26 parameters


const unsigned int radiancePayloadRayDataSemantics[19] =
{
  // RadiancePayloadRayData::attenuation
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE,
  // RadiancePayloadRayData::seed
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE,
  // RadiancePayloadRayData::depth
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE,
  // RadiancePayloadRayData::emitted
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  // RadiancePayloadRayData::radiance
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  // RadiancePayloadRayData::origin
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE,
  // RadiancePayloadRayData::direction
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE,
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE,
  // RadiancePayloadRayData::done
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE,
  // RadiancePayloadRayData::doneReason
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE
};

const unsigned int volumePayloadRayDataSemantics[26] =
{
  // VolumePayloadRayData::attenuation
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //0
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //1
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //2
  // VolumePayloadRayData::seed
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE, //3
  // VolumePayloadRayData::step
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //4
  // VolumePayloadRayData::emitted
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //5
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //6
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //7
  // VolumePayloadRayData::radiance
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //8
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //9
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //10
  // VolumePayloadRayData::origin
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //11
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //12
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //13
  // VolumePayloadRayData::direction
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //14
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //15
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //16
  // VolumePayloadRayData::done
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ | OPTIX_PAYLOAD_SEMANTICS_CH_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_WRITE, //17
  // VolumePayloadRayData::doneReason
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //18
  // VolumePayloadRayData::tmax
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ_WRITE | OPTIX_PAYLOAD_SEMANTICS_MS_READ_WRITE, //19
  // VolumePayloadRayData::volumeAabb -- minX, minY, minZ, maxX, maxY, maxZ
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ | OPTIX_PAYLOAD_SEMANTICS_MS_READ, //20
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ | OPTIX_PAYLOAD_SEMANTICS_MS_READ, //21
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ | OPTIX_PAYLOAD_SEMANTICS_MS_READ, //22
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ | OPTIX_PAYLOAD_SEMANTICS_MS_READ, //23
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ | OPTIX_PAYLOAD_SEMANTICS_MS_READ, //24
  OPTIX_PAYLOAD_SEMANTICS_TRACE_CALLER_WRITE | OPTIX_PAYLOAD_SEMANTICS_CH_READ | OPTIX_PAYLOAD_SEMANTICS_MS_READ  //25
};


struct AreaLight {
  float3 corner;
  float3 v1;
  float3 v2;
  float3 normal;
  float3 emission;
};

struct PathTraceParams {

  unsigned int width;
  unsigned int height;
  unsigned int maxDepth;
  bool useDirectLighting;
  bool useImportanceSampling;
  
  unsigned int currentFrameIdx;
  float4* accumulationBuffer;
  uchar4* frameBuffer;

  unsigned int samplesPerPixel;

  float3 cameraEye;
  float3 cameraU;
  float3 cameraV;
  float3 cameraW;

  AreaLight areaLight;
  OptixTraversableHandle handle;


  float refractiveRoughness;
  float metallicRoughness;


};

struct RayGenerationData {

};

struct MissData {
  float4 backgroundColor;
};

struct HitGroupData {
  BSDFType bsdfType;
  OptixAabb aabb;
  float3 emissionColor;
  float3 diffuseColor;
  float IOR;
  float roughness;
  float metallic;
  float4* vertices;
  uint3* indices;
};

struct ShadingParams
{
  float3 normal;
  float3 hitpoint;
  float3 direction;
  float3 attenuation;
  unsigned int seed;
  float3 origin;
};

struct VolumeSample
{
  float4 rgba;
  float density;
};